open-holidays.endpoints.get-countries.method=GET
open-holidays.endpoints.get-countries.relUrl=https://openholidaysapi.org/Countries

open-holidays.endpoints.get-subdivisions.method=GET
open-holidays.endpoints.get-subdivisions.relUrl=https://openholidaysapi.org/Subdivisions

open-holidays.endpoints.get-school-holidays-by-date.method=GET
open-holidays.endpoints.get-school-holidays-by-date.relUrl=https://openholidaysapi.org/SchoolHolidaysByDate

open-holidays.endpoints.get-public-holidays-by-date.method=GET
open-holidays.endpoints.get-public-holidays-by-date.relUrl=https://openholidaysapi.org/PublicHolidaysByDate

open-holidays.endpoints.get-statistics-school-holidays.method=GET
open-holidays.endpoints.get-statistics-school-holidays.relUrl=https://openholidaysapi.org/Statistics/SchoolHolidays

open-holidays.endpoints.get-statistics-public-holidays.method=GET
open-holidays.endpoints.get-statistics-public-holidays.relUrl=https://openholidaysapi.org/Statistics/PublicHolidays

postman-echo.endpoints.get-echo.method=GET
postman-echo.endpoints.get-echo.relUrl=https://postman-echo.com/get

postman-echo.endpoints.post-echo.method=POST
postman-echo.endpoints.post-echo.relUrl=https://postman-echo.com/post
