apiName=postman-echo

# Short-term kostyl: baseUrl is empty in dev; relUrl values are absolute URLs.
endpoints.get-echo.method=GET
endpoints.get-echo.relUrl=https://postman-echo.com/get

endpoints.post-echo.method=POST
endpoints.post-echo.relUrl=https://postman-echo.com/post
